### ISSUE TITLE
Incorrect pawn moves

### ISSUE THREAD

**Issue by TeamXceleratorDev** [brozeph/node-chess#15]
First, thank you for putting your chess engine on npms.  I built a chess engine a few years ago and was comparing my results with yours for the first 4 plys. I found that the results were slightly off. I wasn't sure which one was incorrect; so, I modified both to output the results in the same format. I then wrote another app to digest the values and determine the differences.  Long story short, the issue was on the chess.js side.  Your logic for pawn movements has a small bug. It's not accounting for potential double-jump if there is also a capture possible.

Try this:  e2e4,a7a5,f1a6,b7b5.  The last move presented is a very valid move which you can verify on another chess app or manually. However, chess.js does not realize this is a valid move. I believe the pawn logic below is getting confused because there is a capture scenario. Though the pawn can... capture, it doesn't have to. It is very legal to still double-jump.

We should definitely sync up sometime. I did a ton of optimization earlier for my chess engine. Feel free to reach out to me. I hope you are able to get this defect fixed soon. I can double check your results again afterwards.

Thanks,
Ronnie
ronnie@teamxcelerator.com

//pawn logic that I found below
// check for double square first move
	if (opt.piece.moveCount === 0 &&
			opt.destSquares.length === 1 &&
			opt.destSquares[0].piece === null) { // Fix for issue #1
		sq = this.board.getNeighborSquare(
			opt.destSquares[0],
			opt.piece.side === piece.SideType.White ?
					board.NeighborType.Above :
					board.NeighborType.Below
		);

		if (!sq.piece) {
			opt.destSquares.push(sq);
		}

**Comment by brozeph** [comment]
@TeamXceleratorDev, thank you for the great find and bug report! I've implemented a fix and published in v0.2.6 - would be great to sync up!

**Comment by TeamXceleratorDev** [comment]
Thanks. Great news. After picking up the latest code, I was able to verify that your results match my engine even after millions of moves. I believe we can have high confidence that the functionality of the engine is working well.
