### ISSUE TITLE
how would I get the piece that's putting the king in check?

### ISSUE THREAD

**Issue by x13machine** [brozeph/node-chess#22]

**Comment by brozeph** [comment]
@x13machine - great feature request!

**Comment by Piterden** [comment]
@x13machine pieces, not a piece...

**Comment by brozeph** [comment]
@x13machine - I've implemented an event named `check` which now exposes the attacking squares... let me know how this works and if you have any suggestions.

**Comment by Piterden** [comment]
Haha! Events are the good feature!

PS Your code style is awesome, @brozeph :wink:

**Comment by brozeph** [comment]
Marking issue as resolved based on comments 👍
