### ISSUE TITLE
Parser cannot handle PGn notation of enPassant+checking

### ISSUE THREAD

**Issue by Diceling** [brozeph/node-chess#43]
When attempting to parse the attached PGN file, the move "gxf3+" could not be parsed properly. 

Parser reduces it to "gf3" instead of "f3", which is in the list of available moves. Likely because it is also a checking move (hence the +). 

[Gibraltar2019-justfailinggame.txt](https://github.com/brozeph/node-chess/files/5527530/Gibraltar2019-justfailinggame.txt)
[Gibraltar2019.txt](https://github.com/brozeph/node-chess/files/5527531/Gibraltar2019.txt)
<img width="1267" alt="Screenshot 2020-11-12 at 01 37 17" src="https://user-images.githubusercontent.com/2835644/98880258-a0afe900-2487-11eb-8be0-41c6d338af31.png">

**Comment by brozeph** [comment]
@Diceling thank you for this excellent defect report! Fixed in `v0.4.6` - added a unit test and verified the fix using the game you posted!

**Comment by Piterden** [comment]
btw, guys https://gist.github.com/Piterden/09626af18e0019a72e42b5216e935f59

**Comment by brozeph** [comment]
Awesome, @Piterden!

**Comment by Piterden** [comment]
Need to improve assertion a bit. Take a look maybe you have any ideas?
