### ISSUE TITLE
Typescript Declaration File for AutoComplete / Intellisense

### ISSUE THREAD

**Issue by dipamsen** [brozeph/node-chess#45]
I created this declaration file for default autocomplete and intellisense in VSCode

https://gist.github.com/010cc6e16f346ec7cc57ae8d7f108190

**Comment by Piterden** [comment]
Why don't you use optional operator `?`, but use `| null` construction instead?

**Comment by dipamsen** [comment]
@Piterden  fixed it

**Comment by brozeph** [comment]
Included in with release `v0.4.6` - verified it's included with the NPM module, as well. I'm not sure I did it all correctly though... welcome feedback if it's not work as expected.
