### ISSUE TITLE
Add Square to capturedPiece (Piece)

### ISSUE THREAD

**Issue by rayfranco** [brozeph/node-chess#51]
It would be nice to have the square of captured piece to avoid calculating variants like enPassant

```
const { move } = this.game.move(algebraic)
if (move.capturedPiece) {
  console.log('Captured Piece', move.capturedPiece.square) // { file: 'd', rank: 5, piece: Pawn }
}
```

I understand this would be recursive adding a Square in a Piece type, but I'd like to find a way to make it simple.

What do you think?

**Comment by brozeph** [comment]
@rayfranco, for enPassant, the move should actually tell you this directly via a field on the move object.

```javascript
const { move } = this.game.move(algebraic);
if (move.enPassant) {
  // do something here...
}
```

Does this help for your use case at all? 

Also, for the captured piece, I can see where it would be useful to have `prevSquare` with the fields you note above. I'll look into this!

**Comment by rayfranco** [comment]
I'm using this field at the moment and do the calculation myself. I just think to avoid this, since you are doing it already, one solution would be to get the square of the captured piece.

My use case is that I sync my board tracking pieces instead of squares. Therefore I can't rely much on your status board and need to get as much information on what's going on on each move.

**Comment by brozeph** [comment]
Linking this issue to #52 - exposing the `enPassant` event to provide both the information about the squares involved and the piece, but to also make it easy to understand when `enPassant` has actually occurred. Looking to include in `v0.4.9`.

**Comment by rayfranco** [comment]
As mentioned in the linked issue, having a global event `capture` with a (new) type `Capture` including a `Square` instance should solve this problem for most use cases. I will close this issue and follow up in #52
