### ISSUE TITLE
Add full events coverage

### ISSUE THREAD

**Issue by rayfranco** [brozeph/node-chess#52]
I'm thinking of this as an enhancement since your objects are already extending an EventEmitter

What do you think of making this library more Events oriented? Would it add much more complexity to it?

This way we could sync a board using events only, and separate controls and feedback from the library.

If this use case seems legit to you, I might dig in.

**Comment by brozeph** [comment]
@rayfranco - solid idea! Please dig in!

**Comment by brozeph** [comment]
@rayfranco - starting to dig in as well for `v0.4.9`. A number of internal events are used, but not exposed on the game clients, so I am cleaning some of that up.

**Comment by rayfranco** [comment]
That is great news ! Thanks for enthusiasm.

Here is a list a events I've been thinking of:

```
'move'
'capture'
'termination'
'promotion'
'check'
```

Termination could be aliased with specific events names like checkmate, stalemate, repetition etc. This would make it easier to use/remember and might be useful to some, but it adds up a load of events to document :)

The class Event might includes these params to fulfill all above cases:

```
type Event {
  move: Move
  prevSquare: Square
  postSquare: Square
  kingSquare: Square
  attackingSquare?: Square
  capturedSquare?: Square // Maybe add this here for clarity?
  isCheckmate: Boolean
  isStalemate: Boolean
  isRepetition: Boolean
  isEnPassant: Boolean
}
```

I think since each event occured after a move, this type makes sense even if all parameters aren't mandatory for all types of events. This would make it consistent and "simple".

Another idea is to add some types for Check, Termination and why not Capture. This would add some work but maybe makes the code more solid when treating these events?

```
type Check {
  kingSquare: Square
  attackingSquare: Square
}
```

```
type Termination {
  isCheckmate: Boolean
  isStalemate: Boolean
  isRepetition: Boolean
}
```

```
type Capture {
  square: Square
  isEnPassant: Boolean
}
```

This would result in a simpler Event type:

```
type Event {
  move: Move
  prevSquare: Square
  postSquare: Square
  check: Check | false
  termination: Termination | false
  Capture: Capture | false
}
```

And while I write this, I'm thinking `prevSquare` / `postSquare` should be implemented in `Move`, and 
`PlayedMove` should simply be a Move. Move could includes the `undo` method and a Capture object . Hopes that is not too confusing.

I'm just writing this as a draft, open for discussion

**Comment by brozeph** [comment]
@rayfranco `v0.4.9` has been published with the new events... the only event I have not added yet is `termination`. 

I kept things fairly consistent with the event types returned to eliminate as much variance as possible (perhaps at the risk of being verbose). How does this work for you?
