### ISSUE TITLE
a small mistake in game.js

### ISSUE THREAD

**Issue by fasafanoff** [brozeph/node-chess#58]
In file game.js on line 90 there should be a board parameter passed to the game object.

**Comment by Piterden** [comment]
Hello,

could you fix it and make pull request please?

**Comment by fasafanoff** [comment]
I'm not very experienced with it, but I'll try to.

> Hello,
> 
> could you fix it and make pull request please?

**Comment by fasafanoff** [comment]
I figured that out!!

**Comment by brozeph** [comment]
@fasafanoff, thank you! I looked more closely and this is one area of the module where we don't have many unit tests (really any at all). This was a defect that was never found!

**Comment by fasafanoff** [comment]
@brozeph, I'm really happy to be useful.
