### ISSUE TITLE
Update moveHistory and notatedMoves when calling undo()

### ISSUE THREAD

**Issue by tomijaga** [brozeph/node-chess#62]
I stored all the played moves and looped through to call `undo()`. 
The board and its pieces update to the previous locations but `game.moveHistory` and `getStatus().notatedMoves ` do not.

I don't know if this was done on purpose or not,  just thought i should report it .

**Comment by brozeph** [comment]
@tomijaga, awesome find here! I shipped a fix in `v0.4.12` which is now available via npmjs!

**Comment by tomijaga** [comment]
@brozeph Thank you for the fix. This will help make my project idea easier to implement
