### ISSUE TITLE
[Question] Why is the pawn piece instantiated with a empty string instead of 'P'?

### ISSUE THREAD

**Issue by alexrintt** [brozeph/node-chess#87]
https://github.com/brozeph/node-chess/blob/93afab6b55bfd504404c0cbe25e0b38e8dcd8b73/src/piece.js#L88

On `Board.load(fen)` function it is represented as 'p' and 'P'; So, why is it represented as an empty string on the `PawnPiece.notation` class field?

I'm rewriting this library in Dart, so I'm wondering if it has some relevance, or may I can replace it with `P`.

TIA.

**Comment by brozeph** [comment]
The primary driver here was because in algebraic  notation, the “P” prefix on chess moves made with a pawn is generally omitted.

**Comment by alexrintt** [comment]
That's it, thx for the fast reply.
